In [1]:
#premise_pathways
import bw2data
import bw2io as bi
from datapackage import Package
import premise as pr
from por_supplier_linking import configure_por_export_support, attach_por_supplier_linking
configure_por_export_support()
import bw2data as bd
import pycountry
import re
import pandas as pd

# Now import shared variables
from config import *
from private_keys import *

#Standard vars
bw2data.projects.set_current(PROJECT_NAME)
pr.__version__,PROJECT_NAME

c:\Users\terlouw_t\.conda\envs\premise_pathways_new\Lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.0.1)/charset_normalizer (3.4.5) doesn't match a supported version!
  warnings.warn(

11:01:39+0200 [warning  ] Can't import `SimaProBlockCSVImporter` - please install `bw2io` with `pip install bw2io[multifunctional]` or install `multifunctional` and `bw_simapro_csv` manually.
Applied premise external-market compatibility fix for empty uncertainty bounds.
Applied export guard for scenarios with validated repo-managed PoR supplier links.
Installed repo Pathways mapping compatibility guard for metals diagnostics.
Installed exact inventory supplier compatibility hooks for configured additional inventories.

((2, 5, 2), 'por')

### 1. Here we decide whether we want to generate a new brightway database or export the databases directly as efficient data packages

In [2]:
create_db_package = True
create_dbs = False

### 1.1 Decide on the scenarios to be included for this exercise:

The non-ferrous metals selector in the next cell is used by **both** export routes. `baseline` preserves the active premise version's native behaviour. `reference` reads fixed reference fractions; `conservative`, `moderate_recycling` and `high_recycling` read minimum-share curves from the scenario files without reducing a higher native share. `primary_only` is a non-ferrous sensitivity. **Steel is not overridden:** its production routes and supply mix remain endogenous to REMIND or the selected EDM-I model.

No separate metals notebook or site-packages edits are required. The notebook prepares and validates the share files in `primary_vs_secondary_metals/scenario_data`, then reads the selected file directly. `high_recycling` reads `primary_secondary_split_optimistic.yaml`; `conservative` reads its namesake; `moderate_recycling` reads the generated `baseline` file, while the selector `baseline` remains native premise. Matching/safeguards stay in `configuration_file/metals_scenario_policy.yaml`. Non-baseline outputs receive a case suffix. See [non-ferrous policy and endogenous steel](docs/metals_scenario_policy.md).

* A business-as-usual scenario, using current trends from output energy system scenarios from OPEN-PROM, EDM-I, FORECAST, and combine without circular economy measures.
* A low-carbon scenario, using low-carbon output energy system scenarios from OPEN-PROM, EDM-I, FORECAST, and combine it to ambitious circular economy measures.

All information is provided in data packages, we import it and define the scenarios below

In [3]:
# One policy selection for both CL/OCE and both Brightway/Pathways exports.
from pathlib import Path
import metals_scenario_policy as metal_policy_module
import primary_vs_secondary_metals.share_files as metal_share_files
NONFERROUS_METALS_SCENARIO = "baseline"  # reference, conservative, moderate_recycling, high_recycling, primary_only
METALS_SHARE_SOURCE = "yaml"  # YAML + evidence/mapping CSV inputs; use xlsx to read the Shares workbook instead
FORCE_METALS_SHARE_REGENERATION = False  # True only to deliberately replace conflicting manual scenario edits
METALS_POLICY_FILE = Path(metal_policy_module.__file__).resolve().parent / "configuration_file/metals_scenario_policy.yaml"
PATHWAYS_PACKAGE_BASENAME = "remind-transience_por"

def load_selected_metal_steel_policy():
    share_preparation = metal_share_files.prepare_policy_share_data(
        METALS_POLICY_FILE, source=METALS_SHARE_SOURCE, force=FORCE_METALS_SHARE_REGENERATION,
    )
    print("Metals share data:", share_preparation.get("status"),
          "; products:", share_preparation.get("product_count"))
    return metal_policy_module.MetalSteelPolicy.from_file(
        METALS_POLICY_FILE, nonferrous_case=NONFERROUS_METALS_SCENARIO,
    )

# Validate the selection before constructing expensive scenario builders.
selected_metal_steel_policy = load_selected_metal_steel_policy()
print("Selected non-ferrous metals:", NONFERROUS_METALS_SCENARIO, "; steel: endogenous REMIND/EDM-I")

sps_op = Package(r"datapackage_open_prom.json")
sps_edm_i = Package(r"datapackage_edm_i.json")
sps_forecast = Package(r"datapackage_forecast.json")
sps_itom_por = Package(r"datapackage_itom_por.json")

bau_iam_scenario = 'SSP2-NDC'#"SSP2-PkBudg1000"
bau_iam_scenario = 'SSP2-PkBudg1000' # this would fit better the OCE and CL scenarios for now

#1. OPEN-PROM file with all energy system info
#2. modifying EU steel sector.
#3. Add FORECAST ammonia and methanol markets in Europe.
#3. Integrate PoR in the Netherlands.

# Low-carbon scenario:
scenarios = [
        {"model": "remind", 'year': 2050, "pathway": bau_iam_scenario, 
         "external scenarios": [
                              #{"scenario": "NDC-EI", "data": sps_op}, #Electricity + hydrogen for Europe, OPEN-PROM
                             #{"scenario": "CBAM", "data": sps_edm_i},  #Steel, EDM-invest (now ITOM, EUROPEAN SCOPE for now)
                              {"scenario": "fc_nz", "data": sps_forecast}, #Methanol + Ammonia, FORECAST is focused on low-carbon scenario (Country-specific scope in EU)
                              {"scenario": "OCE", "data": sps_itom_por}, #PoR from ITOM                                                                           
                                   ] },
        {"model": "remind", 'year': 2050, "pathway": bau_iam_scenario, 
         "external scenarios": [
        #                      {"scenario": "NDC-EI", "data": sps_op}, #Electricity for Europe, OPEN-PROM
        #                     {"scenario": "CBAM", "data": sps_edm_i},  #Steel, EDM-invest (now ITOM, EUROPEAN SCOPE for now)
                              {"scenario": "fc_nz", "data": sps_forecast}, #Methanol + Ammonia, FORECAST is focused on low-carbon scenario (Country-specific scope in EU)
                              {"scenario": "CL", "data": sps_itom_por}, #PoR from ITOM                                                                           
                                   ] },

]

Metals share data: reused ; products: 103
Selected non-ferrous metals: baseline ; steel: endogenous REMIND/EDM-I

In [4]:
# we need to convert ISO3 names to ISO2 for the PoR data using Open-prom, which is in ISO2. We can do this with pycountry.

In [5]:
# Read CSV
df = pd.read_csv("scenario_data/scenario_data_open_prom_init.csv")

def iso3_to_iso2(code):
    try:
        return pycountry.countries.get(alpha_3=code).alpha_2
    except:
        return code  # keep original if not found

df["region"] = df["region"].apply(iso3_to_iso2)

# Save
df.to_csv("scenario_data\scenario_data_open_prom.csv", index=False)

In [6]:
# Create dbs if not existing yet
if DB_NAME_INIT not in bi.databases:
    bi.import_ecoinvent_release("3.12", "cutoff", USER_NAME, USER_PW)
bi.databases

Databases dictionary with 4 object(s):
	ecoinvent-3.12-biosphere
	ecoinvent-3.12-cutoff
	ecoinvent_312_reference
	remind_2050_SSP2-PkBudg1000_fc_nz_OCE

In [7]:
for db in list(bi.databases):
    if db == 'ecoinvent_312_reference':
        pass
        #del bd.databases['ecoinvent_312_reference']
    if 'remind_' in db:
        pass
        #print(f"Deleting {db}...")
        #del bd.databases[db]
list(bi.databases)

['ecoinvent-3.12-biosphere',
 'ecoinvent-3.12-cutoff',
 'ecoinvent_312_reference',
 'remind_2050_SSP2-PkBudg1000_fc_nz_OCE']

In [8]:
# We need to make an additional database with ecoinvent to import LCIs
def generate_reference_database():
    """
    Generate a reference database based on specified parameters.

    This function generates a reference database based on the specified parameters.
    It deletes the existing reference database with the same name if it exists and then creates a new one.

    Returns:
    None

    Example:
    >>> generate_reference_database()
    """

    bd.projects.set_current(PROJECT_NAME)
    pr.clear_cache()
    # Delete old reference database with the same name
    for db_name in list(bi.databases):
        if NAME_REF_DB in db_name:
            print(db_name)
            del bi.databases[db_name]

    # Create a new reference database using NewDatabase
    ndb = pr.NewDatabase(
        scenarios=[{"model": "remind", "pathway": "SSP2-NPi", "year": "2025",
                    "exclude": ["update_electricity", "update_cement", "update_steel", "update_dac",
                                "update_fuels", "update_emissions"]}],
        source_db=DB_NAME_INIT,
        source_version=EI_VERSION,
        key=KEY_PREMISE,
        biosphere_name=BIOSPHERE_DB,
    )

    # Write the new reference database to Brightway2
    ndb.write_db_to_brightway(name=NAME_REF_DB)

if NAME_REF_DB not in bi.databases:
    generate_reference_database()

### 1.4 if we want to export it as a brightway database, we can do this as follows:

In [9]:
def clean(s: str) -> str:
    """Replace spaces with - and ensure it's filename safe."""
    return re.sub(r"\s+", "-", s)

scenario_names = []

for sc in scenarios:
    parts = [sc["model"], str(sc["year"]), sc["pathway"]]
    external = [clean(item["scenario"]) for item in sc["external scenarios"]]
    parts.extend(external)
    scenario_names.append("_".join(parts))
scenario_names

['remind_2050_SSP2-PkBudg1000_fc_nz_OCE',
 'remind_2050_SSP2-PkBudg1000_fc_nz_CL']

In [10]:
if create_dbs:
    import importlib
    import premise_compat as por_compat
    import por_supplier_linking as por_linking
    import metals_scenario_policy as metal_policy_module
    import primary_vs_secondary_metals.share_files as metal_share_files
    importlib.reload(metal_policy_module)
    importlib.reload(metal_share_files)
    importlib.reload(por_compat)
    importlib.reload(por_linking)
    selected_metal_steel_policy = load_selected_metal_steel_policy()
    from por_supplier_linking import configure_por_export_support, attach_por_supplier_linking
    from por_scenario_inputs import fresh_scenario_definitions
    configure_por_export_support()
    bw_scenarios = fresh_scenario_definitions(scenarios[0:1])
    bw_scenario_names = [name + selected_metal_steel_policy.case_suffix for name in scenario_names[0:1]]

    # Build successfully before replacing the existing scenario databases.
    ndb = pr.NewDatabase(
        scenarios = bw_scenarios,
        source_db=DB_NAME_INIT, # <-- name of the database in the BW2 project. Must be a string.
        source_version=EI_VERSION, # <-- version of ecoinvent. Must be a string.
        key=KEY_PREMISE, # <-- ask the key to run premise from the developers
        biosphere_name=BIOSPHERE_DB)

    # Policy runs after native updates, before PoR links and export validation.
    metal_policy_module.attach_metal_steel_policy(ndb, policy=selected_metal_steel_policy, stage="brightway")
    attach_por_supplier_linking(ndb, stage="brightway")
    ndb.update()
    metal_audit_fields = ("year", "external_scenarios", "nonferrous_case", "steel_owner", "changed_markets", "warning_rows", "report_path")
    display(pd.DataFrame([{key: report.get(key) for key in metal_audit_fields}
                          for report in getattr(ndb, "metal_steel_policy_reports", [])]))

    # Check checkpoint readability before any existing target is removed.
    bw_export_preflight = por_linking.preflight_por_brightway_export(ndb)
    print(f"Brightway inventory preflight passed for {len(bw_export_preflight)} scenario(s).", flush=True)
    # Replace only these export targets, preserving unrelated future databases.
    for db in bw_scenario_names:
        if db in bd.databases:
            print(f"Replacing {db} after successful scenario update and inventory preflight")
            del bd.databases[db]

    ndb.write_db_to_brightway(name=bw_scenario_names)

### 2. Export the defined scenarios for chosen years as data packages needed for PATHWAYS in the next step (see `2_calc_impacts.ipynb`)

Classification metadata is captured after updating/linking, **before** premise releases its inventories during matrix export. The package receives a populated CPC/ISIC classification table; detailed assignment sources, provisional rules and conflicts are saved under `export/por_classifications/<snapshot hash>/`. Existing native labels take priority. Explicit foreground rules fill justified gaps; unknowns remain `undefined`, not omitted from impact totals. This changes reporting metadata only, not exchanges or LCIA factors.

Restart the kernel and use a fresh builder after helper changes. See [classification workflow](docs/por_classifications.md) and [rule sources](docs/por_classification_rules_sources.md).

scenarios

In [11]:
if create_db_package:
    import importlib, sys
    import premise_compat as por_compat
    import por_classifications as por_classification_details
    import inventory_supplier_compat as por_inventory_compat
    import por_supplier_linking as por_linking
    import por_scenario_inputs as por_inputs
    import metals_scenario_policy as metal_policy_module
    import primary_vs_secondary_metals.share_files as metal_share_files
    # Ordinary imports keep old helper functions in a long-lived kernel.
    importlib.reload(por_compat)
    importlib.reload(por_classification_details)
    importlib.reload(por_inventory_compat)
    importlib.reload(por_linking)
    importlib.reload(por_inputs)
    importlib.reload(metal_policy_module)
    importlib.reload(metal_share_files)
    selected_metal_steel_policy = load_selected_metal_steel_policy()
    selected_package_name = PATHWAYS_PACKAGE_BASENAME + selected_metal_steel_policy.case_suffix

    print(f"Running premise {getattr(pr, '__version__', 'unknown')} from {getattr(pr, '__file__', 'unknown')}; Python: {sys.executable}", flush=True)

    por_linking.configure_por_export_support()
    package_scenarios = por_inputs.fresh_scenario_definitions(scenarios)
    print("Preparing fresh inputs for the six-year Pathways package...", flush=True)

    #if 'external scenarios' in str(scenario):
    ndb = pr.PathwaysDataPackage(
        scenarios=package_scenarios,
        #years=[2050],
        years=[2025, 2030, 2035, 2040, 2045, 2050],#, 2050],
        source_db=DB_NAME_INIT,
        source_version=EI_VERSION,
        key=KEY_PREMISE,
        biosphere_name=BIOSPHERE_DB )

    # The package calls its internal NewDatabase.update() before exporting matrices.
    print("Package builder ready; attaching the PoR post-update linking step.", flush=True)
    metal_policy_module.attach_metal_steel_policy(ndb.datapackage, policy=selected_metal_steel_policy, stage="pathways")
    metal_policy_module.attach_metal_steel_package_provenance(ndb, policy=selected_metal_steel_policy)
    por_linking.attach_por_pathways_export(ndb, stage="pathways")
    
    ndb.create_datapackage(
        name=selected_package_name,
        contributors=[
            {"name": "Tom Terlouw",
            "email": "tom.terlouw@psi.ch"}] )

    print("Selected archive for notebook 2:", str(Path(selected_package_name + ".zip").resolve()))
    metal_audit_fields = ("year", "external_scenarios", "nonferrous_case", "steel_owner", "changed_markets", "warning_rows", "report_path")
    display(pd.DataFrame([{key: report.get(key) for key in metal_audit_fields}
                          for report in getattr(ndb.datapackage, "metal_steel_policy_reports", [])]))
    # Exported classification metadata comes from the pre-matrix snapshot.
    print("Classification export summary:", ndb.classification_stats)
    print("Classification audit directory:", getattr(ndb, "classification_audit_path", None))
    display(pd.DataFrame(ndb.classification_audit).head(30))

Metals share data: reused ; products: 103
Running premise (2, 5, 2) from c:\Users\terlouw_t\.conda\envs\premise_pathways_new\Lib\site-packages\premise\__init__.py; Python: c:\Users\terlouw_t\.conda\envs\premise_pathways_new\python.exe
Preparing fresh inputs for the six-year Pathways package...
premise v.(2, 5, 2)
+------------------------------------------------------------------+
| Warning                                                          |
+------------------------------------------------------------------+
| Because some of the scenarios can yield LCI databases            |
| containing net negative emission technologies (NET),             |
| it is advised to account for biogenic CO2 flows when calculating |
| Global Warming potential indicators.                             |
| `premise_gwp` provides characterization factors for such flows.  |
| It also provides factors for hydrogen emissions to air.          |
|                                                                  |
| Within your Brightway project:                                   |
| from premise_gwp import add_premise_gwp                          |
| add_premise_gwp()                                                |
+------------------------------------------------------------------+
+--------------------------------+----------------------------------+
| Utils functions                | Description                      |
+--------------------------------+----------------------------------+
| clear_cache()                  | Clears the cache folder. Useful  |
|                                | when updating `premise`or        |
|                                | encountering issues with         |
|                                | inventories.                     |
| get_regions_definition(model)  | Retrieves the list of countries  |
|                                | for each region of the model.    |
| ndb.NewDatabase(...)           | Generates a summary of the most  |
| ndb.generate_scenario_report() | important scenarios' variables.  |
+--------------------------------+----------------------------------+
Keep uncertainty data?
NewDatabase(..., keep_source_db_uncertainty=True), keep_imports_uncertainty=True)

Hide these messages?
NewDatabase(..., quiet=True)
- Extracting source database
- Extracting inventories
- Fetching IAM data
Found file: remind_SSP2-PkBudg1000
Reading remind_SSP2-PkBudg1000 as CSV file
Found file: remind_SSP2-PkBudg1000
Reading remind_SSP2-PkBudg1000 as CSV file
Found file: remind_SSP2-PkBudg1000
Found file: remind_SSP2-PkBudg1000
Found file: remind_SSP2-PkBudg1000
Found file: remind_SSP2-PkBudg1000
Found file: remind_SSP2-PkBudg1000
Found file: remind_SSP2-PkBudg1000
Found file: remind_SSP2-PkBudg1000
Found file: remind_SSP2-PkBudg1000
Found file: remind_SSP2-PkBudg1000
Found file: remind_SSP2-PkBudg1000
Done!
Package builder ready; attaching the PoR post-update linking step.
Attached non-ferrous metals policy (pathways): baseline; native baseline and endogenous steel remain unchanged.
Attached non-ferrous metals package provenance; endogenous steel ownership is recorded in JSON metadata.
Attached PoR supplier linking (pathways); processing starts after premise.update().
Attached concrete Pathways package guard; mapping and classification preflight run before matrix export.

Processing scenarios for all sectors:   0%|    | 0/12 [00:00<?, ?it/s]

Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-forecast.xlsx
Extracted 1 worksheets in 0.01 seconds
Migration route: 3.10 → 3.11 → 3.12
Applying forward migration 3.10 -> 3.11
Applying forward migration 3.11 -> 3.12
Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-itom_por.xlsx
Extracted 1 worksheets in 0.08 seconds
No suppliers found for market for toluene (por) in NL. No market created. This may cause linking issue.
No suppliers found for market for methanol (por) in NL. No market created. This may cause linking issue.
  Native metals audit: scanning activity metadata (no background exchanges)
  Native metals audit: planning 10 selected identity record(s)

Processing scenarios for all sectors:   8%| | 1/12 [01:12<13:14, 72.18

Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-forecast.xlsx
Extracted 1 worksheets in 0.00 seconds
Migration route: 3.10 → 3.11 → 3.12
Applying forward migration 3.10 -> 3.11
Applying forward migration 3.11 -> 3.12
Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-itom_por.xlsx
Extracted 1 worksheets in 0.07 seconds
No suppliers found for market for toluene (por) in NL. No market created. This may cause linking issue.
No suppliers found for market for methanol (por) in NL. No market created. This may cause linking issue.
  Native metals audit: scanning activity metadata (no background exchanges)
  Native metals audit: planning 10 selected identity record(s)

Processing scenarios for all sectors:  17%|▏| 2/12 [02:33<12:56, 77.60

Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-forecast.xlsx
Extracted 1 worksheets in 0.02 seconds
Migration route: 3.10 → 3.11 → 3.12
Applying forward migration 3.10 -> 3.11
Applying forward migration 3.11 -> 3.12
Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-itom_por.xlsx
Extracted 1 worksheets in 0.06 seconds
No suppliers found for market for toluene (por) in NL. No market created. This may cause linking issue.
  Native metals audit: scanning activity metadata (no background exchanges)
  Native metals audit: planning 10 selected identity record(s)

Processing scenarios for all sectors:  25%|▎| 3/12 [03:52<11:42, 78.03

Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-forecast.xlsx
Extracted 1 worksheets in 0.01 seconds
Migration route: 3.10 → 3.11 → 3.12
Applying forward migration 3.10 -> 3.11
Applying forward migration 3.11 -> 3.12
Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-itom_por.xlsx
Extracted 1 worksheets in 0.05 seconds
No suppliers found for market for toluene (por) in NL. No market created. This may cause linking issue.
  Native metals audit: scanning activity metadata (no background exchanges)
  Native metals audit: planning 10 selected identity record(s)

Processing scenarios for all sectors:  33%|▎| 4/12 [05:12<10:32, 79.09

Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-forecast.xlsx
Extracted 1 worksheets in 0.00 seconds
Migration route: 3.10 → 3.11 → 3.12
Applying forward migration 3.10 -> 3.11
Applying forward migration 3.11 -> 3.12
Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-itom_por.xlsx
Extracted 1 worksheets in 0.06 seconds
  Native metals audit: scanning activity metadata (no background exchanges)
  Native metals audit: planning 10 selected identity record(s)

Processing scenarios for all sectors:  42%|▍| 5/12 [06:25<08:57, 76.85

Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-forecast.xlsx
Extracted 1 worksheets in 0.01 seconds
Migration route: 3.10 → 3.11 → 3.12
Applying forward migration 3.10 -> 3.11
Applying forward migration 3.11 -> 3.12
Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-itom_por.xlsx
Extracted 1 worksheets in 0.06 seconds
  Native metals audit: scanning activity metadata (no background exchanges)
  Native metals audit: planning 10 selected identity record(s)

Processing scenarios for all sectors:  50%|▌| 6/12 [07:46<07:50, 78.34

Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-forecast.xlsx
Extracted 1 worksheets in 0.02 seconds
Migration route: 3.10 → 3.11 → 3.12
Applying forward migration 3.10 -> 3.11
Applying forward migration 3.11 -> 3.12
Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-itom_por.xlsx
Extracted 1 worksheets in 0.07 seconds
  Native metals audit: scanning activity metadata (no background exchanges)
  Native metals audit: planning 10 selected identity record(s)

Processing scenarios for all sectors:  58%|▌| 7/12 [09:15<06:49, 81.82

Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-forecast.xlsx
Extracted 1 worksheets in 0.01 seconds
Migration route: 3.10 → 3.11 → 3.12
Applying forward migration 3.10 -> 3.11
Applying forward migration 3.11 -> 3.12
Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-itom_por.xlsx
Extracted 1 worksheets in 0.07 seconds
  Native metals audit: scanning activity metadata (no background exchanges)
  Native metals audit: planning 10 selected identity record(s)

Processing scenarios for all sectors:  67%|▋| 8/12 [10:39<05:29, 82.48

Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-forecast.xlsx
Extracted 1 worksheets in 0.01 seconds
Migration route: 3.10 → 3.11 → 3.12
Applying forward migration 3.10 -> 3.11
Applying forward migration 3.11 -> 3.12
Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-itom_por.xlsx
Extracted 1 worksheets in 0.07 seconds
  Native metals audit: scanning activity metadata (no background exchanges)
  Native metals audit: planning 10 selected identity record(s)

Processing scenarios for all sectors:  75%|▊| 9/12 [12:10<04:15, 85.06

Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-forecast.xlsx
Extracted 1 worksheets in 0.00 seconds
Migration route: 3.10 → 3.11 → 3.12
Applying forward migration 3.10 -> 3.11
Applying forward migration 3.11 -> 3.12
Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-itom_por.xlsx
Extracted 1 worksheets in 0.06 seconds
  Native metals audit: scanning activity metadata (no background exchanges)
  Native metals audit: planning 10 selected identity record(s)

Processing scenarios for all sectors:  83%|▊| 10/12 [13:36<02:50, 85.4

Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-forecast.xlsx
Extracted 1 worksheets in 0.01 seconds
Migration route: 3.10 → 3.11 → 3.12
Applying forward migration 3.10 -> 3.11
Applying forward migration 3.11 -> 3.12
Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-itom_por.xlsx
Extracted 1 worksheets in 0.12 seconds
  Native metals audit: scanning activity metadata (no background exchanges)
  Native metals audit: planning 10 selected identity record(s)

Processing scenarios for all sectors:  92%|▉| 11/12 [15:04<01:26, 86.1

Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-forecast.xlsx
Extracted 1 worksheets in 0.01 seconds
Migration route: 3.10 → 3.11 → 3.12
Applying forward migration 3.10 -> 3.11
Applying forward migration 3.11 -> 3.12
Importing c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\inventories/lci-itom_por.xlsx
Extracted 1 worksheets in 0.06 seconds
  Native metals audit: scanning activity metadata (no background exchanges)
  Native metals audit: planning 10 selected identity record(s)

Processing scenarios for all sectors: 100%|█| 12/12 [16:33<00:00, 82.8

Done!

Non-ferrous metals policy 1/12 — 2025 SSP2-PkBudg1000: planning baseline; steel remains endogenous
Non-ferrous metals policy 2/12 — 2025 SSP2-PkBudg1000: planning baseline; steel remains endogenous
Non-ferrous metals policy 3/12 — 2030 SSP2-PkBudg1000: planning baseline; steel remains endogenous
Non-ferrous metals policy 4/12 — 2030 SSP2-PkBudg1000: planning baseline; steel remains endogenous
Non-ferrous metals policy 5/12 — 2035 SSP2-PkBudg1000: planning baseline; steel remains endogenous
Non-ferrous metals policy 6/12 — 2035 SSP2-PkBudg1000: planning baseline; steel remains endogenous
Non-ferrous metals policy 7/12 — 2040 SSP2-PkBudg1000: planning baseline; steel remains endogenous
Non-ferrous metals policy 8/12 — 2040 SSP2-PkBudg1000: planning baseline; steel remains endogenous
Non-ferrous metals policy 9/12 — 2045 SSP2-PkBudg1000: planning baseline; steel remains endogenous
Non-ferrous metals policy 10/12 — 2045 SSP2-PkBudg1000: planning baseline; steel remains endogenous
Non-ferrous metals policy 11/12 — 2050 SSP2-PkBudg1000: planning baseline; steel remains endogenous
Non-ferrous metals policy 12/12 — 2050 SSP2-PkBudg1000: planning baseline; steel remains endogenous
Non-ferrous metals policy: 12 scenario(s). Native baseline is audit-only; steel is unchanged. Reports: C:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\export\metals_policy\20261015T091912465778Z_34994943
PoR supplier linking 1/12 — 2025 fc_nz + OCE: loading updated inventory
PoR supplier linking 1/12 — 2025 fc_nz + OCE: loading PoR activities and supplier identities
PoR supplier linking 1/12 — 2025 fc_nz + OCE: matching and linking suppliers
PoR supplier linking 1/12 — 2025 fc_nz + OCE: capturing validation baseline
PoR supplier linking 1/12 — 2025 fc_nz + OCE: validating links and cycle changes
PoR supplier linking 1/12 — 2025 fc_nz + OCE: saving linked checkpoint
PoR supplier linking 1/12 — 2025 fc_nz + OCE: ready
PoR supplier linking 1/12 — 2025 fc_nz + OCE: complete (60.2 s; 463 changed exchanges)
PoR supplier linking 2/12 — 2025 fc_nz + CL: loading updated inventory
PoR supplier linking 2/12 — 2025 fc_nz + CL: loading PoR activities and supplier identities
PoR supplier linking 2/12 — 2025 fc_nz + CL: matching and linking suppliers
PoR supplier linking 2/12 — 2025 fc_nz + CL: capturing validation baseline
PoR supplier linking 2/12 — 2025 fc_nz + CL: validating links and cycle changes
PoR supplier linking 2/12 — 2025 fc_nz + CL: saving linked checkpoint
PoR supplier linking 2/12 — 2025 fc_nz + CL: ready
PoR supplier linking 2/12 — 2025 fc_nz + CL: complete (58.9 s; 463 changed exchanges)
PoR supplier linking 3/12 — 2030 fc_nz + OCE: loading updated inventory
PoR supplier linking 3/12 — 2030 fc_nz + OCE: loading PoR activities and supplier identities
PoR supplier linking 3/12 — 2030 fc_nz + OCE: matching and linking suppliers
PoR supplier linking 3/12 — 2030 fc_nz + OCE: capturing validation baseline
PoR supplier linking 3/12 — 2030 fc_nz + OCE: validating links and cycle changes
PoR supplier linking 3/12 — 2030 fc_nz + OCE: saving linked checkpoint
PoR supplier linking 3/12 — 2030 fc_nz + OCE: ready
PoR supplier linking 3/12 — 2030 fc_nz + OCE: complete (59.9 s; 463 changed exchanges)
PoR supplier linking 4/12 — 2030 fc_nz + CL: loading updated inventory
PoR supplier linking 4/12 — 2030 fc_nz + CL: loading PoR activities and supplier identities
PoR supplier linking 4/12 — 2030 fc_nz + CL: matching and linking suppliers
PoR supplier linking 4/12 — 2030 fc_nz + CL: capturing validation baseline
PoR supplier linking 4/12 — 2030 fc_nz + CL: validating links and cycle changes
PoR supplier linking 4/12 — 2030 fc_nz + CL: saving linked checkpoint
PoR supplier linking 4/12 — 2030 fc_nz + CL: ready
PoR supplier linking 4/12 — 2030 fc_nz + CL: complete (60.5 s; 463 changed exchanges)
PoR supplier linking 5/12 — 2035 fc_nz + OCE: loading updated inventory
PoR supplier linking 5/12 — 2035 fc_nz + OCE: loading PoR activities and supplier identities
PoR supplier linking 5/12 — 2035 fc_nz + OCE: matching and linking suppliers
PoR supplier linking 5/12 — 2035 fc_nz + OCE: capturing validation baseline
PoR supplier linking 5/12 — 2035 fc_nz + OCE: validating links and cycle changes
PoR supplier linking 5/12 — 2035 fc_nz + OCE: saving linked checkpoint
PoR supplier linking 5/12 — 2035 fc_nz + OCE: ready
PoR supplier linking 5/12 — 2035 fc_nz + OCE: complete (56.6 s; 463 changed exchanges)
PoR supplier linking 6/12 — 2035 fc_nz + CL: loading updated inventory
PoR supplier linking 6/12 — 2035 fc_nz + CL: loading PoR activities and supplier identities
PoR supplier linking 6/12 — 2035 fc_nz + CL: matching and linking suppliers
PoR supplier linking 6/12 — 2035 fc_nz + CL: capturing validation baseline
PoR supplier linking 6/12 — 2035 fc_nz + CL: validating links and cycle changes
PoR supplier linking 6/12 — 2035 fc_nz + CL: saving linked checkpoint
PoR supplier linking 6/12 — 2035 fc_nz + CL: ready
PoR supplier linking 6/12 — 2035 fc_nz + CL: complete (53.4 s; 463 changed exchanges)
PoR supplier linking 7/12 — 2040 fc_nz + OCE: loading updated inventory
PoR supplier linking 7/12 — 2040 fc_nz + OCE: loading PoR activities and supplier identities
PoR supplier linking 7/12 — 2040 fc_nz + OCE: matching and linking suppliers
PoR supplier linking 7/12 — 2040 fc_nz + OCE: capturing validation baseline
PoR supplier linking 7/12 — 2040 fc_nz + OCE: validating links and cycle changes
PoR supplier linking 7/12 — 2040 fc_nz + OCE: saving linked checkpoint
PoR supplier linking 7/12 — 2040 fc_nz + OCE: ready
PoR supplier linking 7/12 — 2040 fc_nz + OCE: complete (49.3 s; 463 changed exchanges)
PoR supplier linking 8/12 — 2040 fc_nz + CL: loading updated inventory
PoR supplier linking 8/12 — 2040 fc_nz + CL: loading PoR activities and supplier identities
PoR supplier linking 8/12 — 2040 fc_nz + CL: matching and linking suppliers
PoR supplier linking 8/12 — 2040 fc_nz + CL: capturing validation baseline
PoR supplier linking 8/12 — 2040 fc_nz + CL: validating links and cycle changes
PoR supplier linking 8/12 — 2040 fc_nz + CL: saving linked checkpoint
PoR supplier linking 8/12 — 2040 fc_nz + CL: ready
PoR supplier linking 8/12 — 2040 fc_nz + CL: complete (48.6 s; 463 changed exchanges)
PoR supplier linking 9/12 — 2045 fc_nz + OCE: loading updated inventory
PoR supplier linking 9/12 — 2045 fc_nz + OCE: loading PoR activities and supplier identities
PoR supplier linking 9/12 — 2045 fc_nz + OCE: matching and linking suppliers
PoR supplier linking 9/12 — 2045 fc_nz + OCE: capturing validation baseline
PoR supplier linking 9/12 — 2045 fc_nz + OCE: validating links and cycle changes
PoR supplier linking 9/12 — 2045 fc_nz + OCE: saving linked checkpoint
PoR supplier linking 9/12 — 2045 fc_nz + OCE: ready
PoR supplier linking 9/12 — 2045 fc_nz + OCE: complete (50.8 s; 463 changed exchanges)
PoR supplier linking 10/12 — 2045 fc_nz + CL: loading updated inventory
PoR supplier linking 10/12 — 2045 fc_nz + CL: loading PoR activities and supplier identities
PoR supplier linking 10/12 — 2045 fc_nz + CL: matching and linking suppliers
PoR supplier linking 10/12 — 2045 fc_nz + CL: capturing validation baseline
PoR supplier linking 10/12 — 2045 fc_nz + CL: validating links and cycle changes
PoR supplier linking 10/12 — 2045 fc_nz + CL: saving linked checkpoint
PoR supplier linking 10/12 — 2045 fc_nz + CL: ready
PoR supplier linking 10/12 — 2045 fc_nz + CL: complete (52.4 s; 463 changed exchanges)
PoR supplier linking 11/12 — 2050 fc_nz + OCE: loading updated inventory
PoR supplier linking 11/12 — 2050 fc_nz + OCE: loading PoR activities and supplier identities
PoR supplier linking 11/12 — 2050 fc_nz + OCE: matching and linking suppliers
PoR supplier linking 11/12 — 2050 fc_nz + OCE: capturing validation baseline
PoR supplier linking 11/12 — 2050 fc_nz + OCE: validating links and cycle changes
PoR supplier linking 11/12 — 2050 fc_nz + OCE: saving linked checkpoint
PoR supplier linking 11/12 — 2050 fc_nz + OCE: ready
PoR supplier linking 11/12 — 2050 fc_nz + OCE: complete (56.9 s; 463 changed exchanges)
PoR supplier linking 12/12 — 2050 fc_nz + CL: loading updated inventory
PoR supplier linking 12/12 — 2050 fc_nz + CL: loading PoR activities and supplier identities
PoR supplier linking 12/12 — 2050 fc_nz + CL: matching and linking suppliers
PoR supplier linking 12/12 — 2050 fc_nz + CL: capturing validation baseline
PoR supplier linking 12/12 — 2050 fc_nz + CL: validating links and cycle changes
PoR supplier linking 12/12 — 2050 fc_nz + CL: saving linked checkpoint
PoR supplier linking 12/12 — 2050 fc_nz + CL: ready
PoR supplier linking 12/12 — 2050 fc_nz + CL: complete (50.2 s; 463 changed exchanges)
PoR supplier linking: 12 scenario(s), 5556 changed exchange(s). Reports: C:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\export\por_supplier_linking
Capturing complete activity classifications before matrix export...
Capturing classifications for scenario 1/12: remind/SSP2-PkBudg1000/2025/0
Capturing classifications for scenario 2/12: remind/SSP2-PkBudg1000/2025/1
Capturing classifications for scenario 3/12: remind/SSP2-PkBudg1000/2030/2
Capturing classifications for scenario 4/12: remind/SSP2-PkBudg1000/2030/3
Capturing classifications for scenario 5/12: remind/SSP2-PkBudg1000/2035/4
Capturing classifications for scenario 6/12: remind/SSP2-PkBudg1000/2035/5
Capturing classifications for scenario 7/12: remind/SSP2-PkBudg1000/2040/6
Capturing classifications for scenario 8/12: remind/SSP2-PkBudg1000/2040/7
Capturing classifications for scenario 9/12: remind/SSP2-PkBudg1000/2045/8
Capturing classifications for scenario 10/12: remind/SSP2-PkBudg1000/2045/9
Capturing classifications for scenario 11/12: remind/SSP2-PkBudg1000/2050/10
Capturing classifications for scenario 12/12: remind/SSP2-PkBudg1000/2050/11
Pathways mapping preflight passed for 12 scenario(s); 24 diagnostic entries excluded.
Write new database(s) to matrix.
Matrices saved in c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\pathways_temp\inventories\remind\SSP2-PkBudg1000-fc_nz-OCE\2025.
Matrices saved in c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\pathways_temp\inventories\remind\SSP2-PkBudg1000-fc_nz-CL\2025.
Matrices saved in c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\pathways_temp\inventories\remind\SSP2-PkBudg1000-fc_nz-OCE\2030.
Matrices saved in c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\pathways_temp\inventories\remind\SSP2-PkBudg1000-fc_nz-CL\2030.
Matrices saved in c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\pathways_temp\inventories\remind\SSP2-PkBudg1000-fc_nz-OCE\2035.
Matrices saved in c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\pathways_temp\inventories\remind\SSP2-PkBudg1000-fc_nz-CL\2035.
Matrices saved in c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\pathways_temp\inventories\remind\SSP2-PkBudg1000-fc_nz-OCE\2040.
Matrices saved in c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\pathways_temp\inventories\remind\SSP2-PkBudg1000-fc_nz-CL\2040.
Matrices saved in c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\pathways_temp\inventories\remind\SSP2-PkBudg1000-fc_nz-OCE\2045.
Matrices saved in c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\pathways_temp\inventories\remind\SSP2-PkBudg1000-fc_nz-CL\2045.
Matrices saved in c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\pathways_temp\inventories\remind\SSP2-PkBudg1000-fc_nz-OCE\2050.
Matrices saved in c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\pathways_temp\inventories\remind\SSP2-PkBudg1000-fc_nz-CL\2050.
Generate scenario report.
Report saved under c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\export\scenario_report.
Generate change report.
Pathways mapping: excluded 24 metals diagnostic entries; activity mappings retained.
Data package saved at c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\remind-transience_por.zip
Selected archive for notebook 2: C:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\remind-transience_por.zip

,year,external_scenarios,nonferrous_case,steel_owner,changed_markets,warning_rows,report_path
0,2025,"[fc_nz, OCE]",baseline,endogenous,0,0,C:\Users\terlouw_t\Documents\Projects\TRANSIEN...
1,2025,"[fc_nz, CL]",baseline,endogenous,0,0,C:\Users\terlouw_t\Documents\Projects\TRANSIEN...
2,2030,"[fc_nz, OCE]",baseline,endogenous,0,0,C:\Users\terlouw_t\Documents\Projects\TRANSIEN...
3,2030,"[fc_nz, CL]",baseline,endogenous,0,0,C:\Users\terlouw_t\Documents\Projects\TRANSIEN...
4,2035,"[fc_nz, OCE]",baseline,endogenous,0,0,C:\Users\terlouw_t\Documents\Projects\TRANSIEN...
5,2035,"[fc_nz, CL]",baseline,endogenous,0,0,C:\Users\terlouw_t\Documents\Projects\TRANSIEN...
6,2040,"[fc_nz, OCE]",baseline,endogenous,0,0,C:\Users\terlouw_t\Documents\Projects\TRANSIEN...
7,2040,"[fc_nz, CL]",baseline,endogenous,0,0,C:\Users\terlouw_t\Documents\Projects\TRANSIEN...
8,2045,"[fc_nz, OCE]",baseline,endogenous,0,0,C:\Users\terlouw_t\Documents\Projects\TRANSIEN...
9,2045,"[fc_nz, CL]",baseline,endogenous,0,0,C:\Users\terlouw_t\Documents\Projects\TRANSIEN...
10,2050,"[fc_nz, OCE]",baseline,endogenous,0,0,C:\Users\terlouw_t\Documents\Projects\TRANSIEN...
11,2050,"[fc_nz, CL]",baseline,endogenous,0,0,C:\Users\terlouw_t\Documents\Projects\TRANSIEN...

Classification export summary: {'activity_count': 515924, 'unique_pairs': 14048, 'classification_rows': 32567, 'undefined_pairs': {'CPC': 4, 'ISIC rev.4 ecoinvent': 123}, 'status_counts': {'original_metadata': 32185, 'provisional': 165, 'undefined': 114, 'conflicting_metadata': 22, 'normalized_reference': 19, 'exact_reference': 62}, 'conflicts': 22, 'ambiguous_reference_entries': 41, 'scenario_count': 12}
Classification audit directory: c:\Users\terlouw_t\Documents\Projects\TRANSIENCE\lca_transience\export\por_classifications\d5ef3cad0800235b

,name,reference product,classification_system,classification_code,status,source,rule_id,reference_name,reference_product,reason,units,locations,scenarios,activity_count
0,"(CF3SO2)2NH production, for LiS battery",(CF3SO2)2NH,CPC,46410: Primary cells and primary batteries,original_metadata,scenario_metadata,,"(CF3SO2)2NH production, for LiS battery",(CF3SO2)2NH,Preserved dataset classification metadata.,kilogram,GLO,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
1,"(CF3SO2)2NH production, for LiS battery",(CF3SO2)2NH,ISIC rev.4 ecoinvent,2720:Manufacture of batteries and accumulators,original_metadata,scenario_metadata,,"(CF3SO2)2NH production, for LiS battery",(CF3SO2)2NH,Preserved dataset classification metadata.,kilogram,GLO,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
2,"(CF3SO2)2NNa production, for LiS battery",(CF3SO2)2NNa,CPC,46410: Primary cells and primary batteries,original_metadata,scenario_metadata,,"(CF3SO2)2NNa production, for LiS battery",(CF3SO2)2NNa,Preserved dataset classification metadata.,kilogram,GLO,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
3,"(CF3SO2)2NNa production, for LiS battery",(CF3SO2)2NNa,ISIC rev.4 ecoinvent,2720:Manufacture of batteries and accumulators,original_metadata,scenario_metadata,,"(CF3SO2)2NNa production, for LiS battery",(CF3SO2)2NNa,Preserved dataset classification metadata.,kilogram,GLO,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
4,"(Me3Si)2NH production, for LiS battery",(Me3Si)2NH,CPC,46410: Primary cells and primary batteries,original_metadata,scenario_metadata,,"(Me3Si)2NH production, for LiS battery",(Me3Si)2NH,Preserved dataset classification metadata.,kilogram,GLO,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
5,"(Me3Si)2NH production, for LiS battery",(Me3Si)2NH,ISIC rev.4 ecoinvent,2720:Manufacture of batteries and accumulators,original_metadata,scenario_metadata,,"(Me3Si)2NH production, for LiS battery",(Me3Si)2NH,Preserved dataset classification metadata.,kilogram,GLO,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
6,"1,1,1-trichloroethane production, vinyl chlori...","1,1,1-trichloroethane",CPC,"3411: Hydrocarbons and their halogenated, sulp...",original_metadata,scenario_metadata,,"1,1,1-trichloroethane production, vinyl chlori...","1,1,1-trichloroethane",Preserved dataset classification metadata.,kilogram,GLO,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
7,"1,1,1-trichloroethane production, vinyl chlori...","1,1,1-trichloroethane",ISIC rev.4 ecoinvent,2011:Manufacture of basic chemicals,original_metadata,scenario_metadata,,"1,1,1-trichloroethane production, vinyl chlori...","1,1,1-trichloroethane",Preserved dataset classification metadata.,kilogram,GLO,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
8,"1,1,2-trichloroethane production, vinyl chlori...","1,1,2-trichloroethane",CPC,"3411: Hydrocarbons and their halogenated, sulp...",original_metadata,scenario_metadata,,"1,1,2-trichloroethane production, vinyl chlori...","1,1,2-trichloroethane",Preserved dataset classification metadata.,kilogram,GLO,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
9,"1,1,2-trichloroethane production, vinyl chlori...","1,1,2-trichloroethane",ISIC rev.4 ecoinvent,2011:Manufacture of basic chemicals,original_metadata,scenario_metadata,,"1,1,2-trichloroethane production, vinyl chlori...","1,1,2-trichloroethane",Preserved dataset classification metadata.,kilogram,GLO,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
10,"1,1-difluoroethane production","1,1-difluoroethane",CPC,"34110: Hydrocarbons and their halogenated, sul...",original_metadata,scenario_metadata,,"1,1-difluoroethane production","1,1-difluoroethane",Preserved dataset classification metadata.,kilogram,RoW; US,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,24
11,"1,1-difluoroethane production","1,1-difluoroethane",EcoSpold01Categories,chemicals/organics,original_metadata,scenario_metadata,,"1,1-difluoroethane production","1,1-difluoroethane",Preserved dataset classification metadata.,kilogram,RoW; US,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,24
12,"1,1-difluoroethane production","1,1-difluoroethane",ISIC rev.4 ecoinvent,2011:Manufacture of basic chemicals,original_metadata,scenario_metadata,,"1,1-difluoroethane production","1,1-difluoroethane",Preserved dataset classification metadata.,kilogram,RoW; US,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,24
13,"1,1-difluoroethane production, hfc-152a","1,1-difluoroethane, hfc-152a",CPC,34150: Amine-function compounds; oxygen-functi...,original_metadata,scenario_metadata,,"1,1-difluoroethane production, hfc-152a","1,1-difluoroethane, hfc-152a",Preserved dataset classification metadata.,kilogram,US,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
14,"1,1-difluoroethane production, hfc-152a","1,1-difluoroethane, hfc-152a",ISIC rev.4 ecoinvent,2011:Manufacture of basic chemicals,original_metadata,scenario_metadata,,"1,1-difluoroethane production, hfc-152a","1,1-difluoroethane, hfc-152a",Preserved dataset classification metadata.,kilogram,US,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
15,"1,1-dimethylcyclopentane to generic market for...","solvent, organic",CPC,341: Basic organic chemicals,original_metadata,scenario_metadata,,"1,1-dimethylcyclopentane to generic market for...","solvent, organic",Preserved dataset classification metadata.,kilogram,GLO,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
16,"1,1-dimethylcyclopentane to generic market for...","solvent, organic",ISIC rev.4 ecoinvent,20:Manufacture of chemicals and chemical products,original_metadata,scenario_metadata,,"1,1-dimethylcyclopentane to generic market for...","solvent, organic",Preserved dataset classification metadata.,kilogram,GLO,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
17,"1,2-Dichloro-1,1-difluoroethane (R-132b) produ...",r-132b,CPC,"34110: Hydrocarbons and their halogenated, sul...",original_metadata,scenario_metadata,,"1,2-Dichloro-1,1-difluoroethane (R-132b) produ...",r-132b,Preserved dataset classification metadata.,kilogram,RER,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
18,"1,2-Dichloro-1,1-difluoroethane (R-132b) produ...",r-132b,ISIC rev.4 ecoinvent,2011:Manufacture of basic chemicals,original_metadata,scenario_metadata,,"1,2-Dichloro-1,1-difluoroethane (R-132b) produ...",r-132b,Preserved dataset classification metadata.,kilogram,RER,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
19,"1,3-dichloropropene to generic market for pest...","pesticide, unspecified",CPC,"3466: Insecticides, fungicides, herbicides and...",original_metadata,scenario_metadata,,"1,3-dichloropropene to generic market for pest...","pesticide, unspecified",Preserved dataset classification metadata.,kilogram,GLO,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
20,"1,3-dichloropropene to generic market for pest...","pesticide, unspecified",ISIC rev.4 ecoinvent,2011:Manufacture of basic chemicals,original_metadata,scenario_metadata,,"1,3-dichloropropene to generic market for pest...","pesticide, unspecified",Preserved dataset classification metadata.,kilogram,GLO,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
21,"1,4-butanediol production","1,4-butanediol",CPC,"34139: Other alcohols, phenols, phenol-alcohol...",original_metadata,scenario_metadata,,"1,4-butanediol production","1,4-butanediol",Preserved dataset classification metadata.,kilogram,NL; RER; RoW,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,36
22,"1,4-butanediol production","1,4-butanediol",EcoSpold01Categories,chemicals/organics,original_metadata,scenario_metadata,,"1,4-butanediol production","1,4-butanediol",Preserved dataset classification metadata.,kilogram,NL; RER; RoW,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,36
23,"1,4-butanediol production","1,4-butanediol",ISIC rev.4 ecoinvent,2011:Manufacture of basic chemicals,original_metadata,scenario_metadata,,"1,4-butanediol production","1,4-butanediol",Preserved dataset classification metadata.,kilogram,NL; RER; RoW,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,36
24,"1,4-butanediol production, fermentation, wheat...","1,4-butanediol, bio-based",CPC,"34139: Other alcohols, phenols, phenol-alcohol...",provisional,"Ecoinvent 3.12 methanol/1,4-butanediol product...",por_bio_butanediol,"1,4-butanediol production","1,4-butanediol",Same defined butanediol chemical product with ...,kilogram,IT,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
25,"1,4-butanediol production, fermentation, wheat...","1,4-butanediol, bio-based",EcoSpold01Categories,chemicals/organics,provisional,"Ecoinvent 3.12 methanol/1,4-butanediol product...",por_bio_butanediol,"1,4-butanediol production","1,4-butanediol",Same defined butanediol chemical product with ...,kilogram,IT,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
26,"1,4-butanediol production, fermentation, wheat...","1,4-butanediol, bio-based",ISIC rev.4 ecoinvent,2011:Manufacture of basic chemicals,provisional,"Ecoinvent 3.12 methanol/1,4-butanediol product...",por_bio_butanediol,"1,4-butanediol production","1,4-butanediol",Same defined butanediol chemical product with ...,kilogram,IT,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
27,"1-chloro-1,1-difluoroethane production, 1,1,1-...","1-chloro-1,1-difluoroethane",CPC,"3411: Hydrocarbons and their halogenated, sulp...",original_metadata,scenario_metadata,,"1-chloro-1,1-difluoroethane production, 1,1,1-...","1-chloro-1,1-difluoroethane",Preserved dataset classification metadata.,kilogram,GLO,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
28,"1-chloro-1,1-difluoroethane production, 1,1,1-...","1-chloro-1,1-difluoroethane",ISIC rev.4 ecoinvent,2011:Manufacture of basic chemicals,original_metadata,scenario_metadata,,"1-chloro-1,1-difluoroethane production, 1,1,1-...","1-chloro-1,1-difluoroethane",Preserved dataset classification metadata.,kilogram,GLO,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12
29,"1-chloro-1,1-difluoroethane production, 1,1,1-...","hydrochloric acid, without water, in 30% solut...",CPC,34231: Chemical elements n.e.c.; inorganic aci...,original_metadata,scenario_metadata,,"1-chloro-1,1-difluoroethane production, 1,1,1-...","hydrochloric acid, without water, in 30% solut...",Preserved dataset classification metadata.,kilogram,GLO,remind/SSP2-PkBudg1000/2025/0; remind/SSP2-PkB...,12

### 3. Continue in Notebook `2_calc_impacts.ipynb` to calculate environmental burdens of sectors or entire energy system scenarios using the exported data packages from the previous step